apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: my-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
      - name: my-website
        image: niranjanative/hello-devops:v3
        ports:
        - containerPort: 8080