apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: my-website-svc
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-website